package com.by.dubbo.admin.domain;

import java.util.Date;

public class App {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_desc
     *
     * @mbg.generated
     */
    private String appDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_principal
     *
     * @mbg.generated
     */
    private String appPrincipal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_principal_name
     *
     * @mbg.generated
     */
    private String appPrincipalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_participators
     *
     * @mbg.generated
     */
    private String appParticipators;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_participators_name
     *
     * @mbg.generated
     */
    private String appParticipatorsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.department_id
     *
     * @mbg.generated
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.department_name
     *
     * @mbg.generated
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.id
     *
     * @return the value of app.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.id
     *
     * @param id the value for app.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_name
     *
     * @return the value of app.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_name
     *
     * @param appName the value for app.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_desc
     *
     * @return the value of app.app_desc
     *
     * @mbg.generated
     */
    public String getAppDesc() {
        return appDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_desc
     *
     * @param appDesc the value for app.app_desc
     *
     * @mbg.generated
     */
    public void setAppDesc(String appDesc) {
        this.appDesc = appDesc == null ? null : appDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_principal
     *
     * @return the value of app.app_principal
     *
     * @mbg.generated
     */
    public String getAppPrincipal() {
        return appPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_principal
     *
     * @param appPrincipal the value for app.app_principal
     *
     * @mbg.generated
     */
    public void setAppPrincipal(String appPrincipal) {
        this.appPrincipal = appPrincipal == null ? null : appPrincipal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_principal_name
     *
     * @return the value of app.app_principal_name
     *
     * @mbg.generated
     */
    public String getAppPrincipalName() {
        return appPrincipalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_principal_name
     *
     * @param appPrincipalName the value for app.app_principal_name
     *
     * @mbg.generated
     */
    public void setAppPrincipalName(String appPrincipalName) {
        this.appPrincipalName = appPrincipalName == null ? null : appPrincipalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_participators
     *
     * @return the value of app.app_participators
     *
     * @mbg.generated
     */
    public String getAppParticipators() {
        return appParticipators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_participators
     *
     * @param appParticipators the value for app.app_participators
     *
     * @mbg.generated
     */
    public void setAppParticipators(String appParticipators) {
        this.appParticipators = appParticipators == null ? null : appParticipators.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.app_participators_name
     *
     * @return the value of app.app_participators_name
     *
     * @mbg.generated
     */
    public String getAppParticipatorsName() {
        return appParticipatorsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.app_participators_name
     *
     * @param appParticipatorsName the value for app.app_participators_name
     *
     * @mbg.generated
     */
    public void setAppParticipatorsName(String appParticipatorsName) {
        this.appParticipatorsName = appParticipatorsName == null ? null : appParticipatorsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.department_id
     *
     * @return the value of app.department_id
     *
     * @mbg.generated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.department_id
     *
     * @param departmentId the value for app.department_id
     *
     * @mbg.generated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.department_name
     *
     * @return the value of app.department_name
     *
     * @mbg.generated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.department_name
     *
     * @param departmentName the value for app.department_name
     *
     * @mbg.generated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.create_time
     *
     * @return the value of app.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.create_time
     *
     * @param createTime the value for app.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.update_time
     *
     * @return the value of app.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.update_time
     *
     * @param updateTime the value for app.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.operator
     *
     * @return the value of app.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.operator
     *
     * @param operator the value for app.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.operator_name
     *
     * @return the value of app.operator_name
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.operator_name
     *
     * @param operatorName the value for app.operator_name
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.status
     *
     * @return the value of app.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.status
     *
     * @param status the value for app.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}