package com.by.dubbo.admin.domain;

import java.util.Date;

public class Dictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.dict_name
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.dict_desc
     *
     * @mbg.generated
     */
    private String dictDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.dict_key
     *
     * @mbg.generated
     */
    private String dictKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.dict_value
     *
     * @mbg.generated
     */
    private String dictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.dict_type
     *
     * @mbg.generated
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.id
     *
     * @return the value of dictionary.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.id
     *
     * @param id the value for dictionary.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.dict_name
     *
     * @return the value of dictionary.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.dict_name
     *
     * @param dictName the value for dictionary.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.dict_desc
     *
     * @return the value of dictionary.dict_desc
     *
     * @mbg.generated
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.dict_desc
     *
     * @param dictDesc the value for dictionary.dict_desc
     *
     * @mbg.generated
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc == null ? null : dictDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.dict_key
     *
     * @return the value of dictionary.dict_key
     *
     * @mbg.generated
     */
    public String getDictKey() {
        return dictKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.dict_key
     *
     * @param dictKey the value for dictionary.dict_key
     *
     * @mbg.generated
     */
    public void setDictKey(String dictKey) {
        this.dictKey = dictKey == null ? null : dictKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.dict_value
     *
     * @return the value of dictionary.dict_value
     *
     * @mbg.generated
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.dict_value
     *
     * @param dictValue the value for dictionary.dict_value
     *
     * @mbg.generated
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.dict_type
     *
     * @return the value of dictionary.dict_type
     *
     * @mbg.generated
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.dict_type
     *
     * @param dictType the value for dictionary.dict_type
     *
     * @mbg.generated
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.create_time
     *
     * @return the value of dictionary.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.create_time
     *
     * @param createTime the value for dictionary.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.update_time
     *
     * @return the value of dictionary.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.update_time
     *
     * @param updateTime the value for dictionary.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.operator
     *
     * @return the value of dictionary.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.operator
     *
     * @param operator the value for dictionary.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.operator_name
     *
     * @return the value of dictionary.operator_name
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.operator_name
     *
     * @param operatorName the value for dictionary.operator_name
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.status
     *
     * @return the value of dictionary.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.status
     *
     * @param status the value for dictionary.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}