package com.by.dubbo.admin.domain;

import java.util.Date;

public class Router {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.router_name
     *
     * @mbg.generated
     */
    private String routerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.router_desc
     *
     * @mbg.generated
     */
    private String routerDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.router_content
     *
     * @mbg.generated
     */
    private String routerContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.service_id
     *
     * @mbg.generated
     */
    private Integer serviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.service_name
     *
     * @mbg.generated
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.app_id
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.approval_status
     *
     * @mbg.generated
     */
    private String approvalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column router.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.id
     *
     * @return the value of router.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.id
     *
     * @param id the value for router.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.router_name
     *
     * @return the value of router.router_name
     *
     * @mbg.generated
     */
    public String getRouterName() {
        return routerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.router_name
     *
     * @param routerName the value for router.router_name
     *
     * @mbg.generated
     */
    public void setRouterName(String routerName) {
        this.routerName = routerName == null ? null : routerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.router_desc
     *
     * @return the value of router.router_desc
     *
     * @mbg.generated
     */
    public String getRouterDesc() {
        return routerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.router_desc
     *
     * @param routerDesc the value for router.router_desc
     *
     * @mbg.generated
     */
    public void setRouterDesc(String routerDesc) {
        this.routerDesc = routerDesc == null ? null : routerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.router_content
     *
     * @return the value of router.router_content
     *
     * @mbg.generated
     */
    public String getRouterContent() {
        return routerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.router_content
     *
     * @param routerContent the value for router.router_content
     *
     * @mbg.generated
     */
    public void setRouterContent(String routerContent) {
        this.routerContent = routerContent == null ? null : routerContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.service_id
     *
     * @return the value of router.service_id
     *
     * @mbg.generated
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.service_id
     *
     * @param serviceId the value for router.service_id
     *
     * @mbg.generated
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.service_name
     *
     * @return the value of router.service_name
     *
     * @mbg.generated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.service_name
     *
     * @param serviceName the value for router.service_name
     *
     * @mbg.generated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.app_id
     *
     * @return the value of router.app_id
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.app_id
     *
     * @param appId the value for router.app_id
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.app_name
     *
     * @return the value of router.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.app_name
     *
     * @param appName the value for router.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.create_time
     *
     * @return the value of router.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.create_time
     *
     * @param createTime the value for router.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.update_time
     *
     * @return the value of router.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.update_time
     *
     * @param updateTime the value for router.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.operator
     *
     * @return the value of router.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.operator
     *
     * @param operator the value for router.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.operator_name
     *
     * @return the value of router.operator_name
     *
     * @mbg.generated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.operator_name
     *
     * @param operatorName the value for router.operator_name
     *
     * @mbg.generated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.type
     *
     * @return the value of router.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.type
     *
     * @param type the value for router.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.approval_status
     *
     * @return the value of router.approval_status
     *
     * @mbg.generated
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.approval_status
     *
     * @param approvalStatus the value for router.approval_status
     *
     * @mbg.generated
     */
    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus == null ? null : approvalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column router.status
     *
     * @return the value of router.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column router.status
     *
     * @param status the value for router.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}