package com.by.dubbo.admin.dao.mapper;

import com.by.dubbo.admin.domain.Alert;

public interface AlertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert
     *
     * @mbg.generated
     */
    int insert(Alert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert
     *
     * @mbg.generated
     */
    int insertSelective(Alert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert
     *
     * @mbg.generated
     */
    Alert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Alert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Alert record);
}