package com.by.dubbo.admin.dao.mapper;

import com.by.dubbo.admin.domain.Router;

public interface RouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbg.generated
     */
    int insert(Router record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbg.generated
     */
    int insertSelective(Router record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbg.generated
     */
    Router selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Router record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table router
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Router record);
}